<?php

use Drupal\node\Entity\NodeType;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\ga_pageviews_counter\GoogleAnalyticsCounter;

/**
 * Implements hook_entity_extra_field_info().
 */
function ga_pageviews_counter_entity_extra_field_info() {
  $extra = [];
  foreach (NodeType::loadMultiple() as $bundle) {
    $extra['node'][$bundle->Id()]['display']['ga_pageviews_counter'] = [
      'label'       => t('Pageviews Counter'),
      'description' => t('Google Analytics Pageviews Counter'),
      'weight'      => 100,
      'visible'     => TRUE,
    ];
  }
  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function ga_pageviews_counter_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($display->getComponent('ga_pageviews_counter')) {
    $count = (new GoogleAnalyticsCounter())->getPageviews($entity);
    $build['ga_pageviews_counter'] = [
      '#type'   => 'markup',
      '#markup' => '<div class="page-views-counter">' . t('Views: @count', ['@count' => $count]) . '</div>',
    ];
  }
}

/**
 * Implements hook_node_presave().
 */
function ga_pageviews_counter_entity_delete(EntityInterface $entity) {
  (new GoogleAnalyticsCounter())->deletePageviews($entity);
}

/**
 * Implements hook_cron().
 */
function ga_pageviews_counter_cron() {
  $last_check = \Drupal::state()->get('ga_pageviews_counter.last_check', 0);
  if (REQUEST_TIME > $last_check + 86400) {
    (new GoogleAnalyticsCounter())->fetchData();
    \Drupal::state()->set('ga_pageviews_counter.last_check', REQUEST_TIME);
  }
}

/**
 * Implements hook_views_data().
 */
function ga_pageviews_counter_views_data() {
  $data = [];
  $data['ga_pageviews_counter'] = [];
  $data['ga_pageviews_counter']['table'] = [];
  $data['ga_pageviews_counter']['table']['group'] = t('Google Analytics Pageviews Counter');
  $data['ga_pageviews_counter']['table']['provider'] = 'ga_pageviews_counter';
  $data['ga_pageviews_counter']['table']['base'] = [
    'field'  => 'entity_id',
    'title'  => t('Google Analytics Pageviews Counter'),
    'help'   => t('Contains GA statistics (pageviews) from your Google Analytics account.'),
    'weight' => -10,
  ];
  $data['ga_pageviews_counter']['table']['join'] = [
    'node_field_data' => [
      'left_field' => 'nid',
      'field'      => 'entity_id',
    ],
  ];
  $data['ga_pageviews_counter']['entity_id'] = [
    'title'        => t('GA Pageviews Counter Node'),
    'help'         => t('Relate GA Pageviews Counter content to the node content'),
    'relationship' => [
      'base'       => 'node_field_data',
      'base field' => 'nid',
      'id'         => 'standard',
      'label'      => t('Node ID'),
    ],
  ];
  $data['ga_pageviews_counter']['bundle'] = [
    'title' => t('Bundle'),
    'help'  => t('Bundle Name.'),
    'field' => [
      'id' => 'standard',
    ],
    'sort' => [
      'id' => 'standard',
    ],
    'filter' => [
      'id' => 'string',
    ],
    'argument' => [
      'id' => 'string',
    ],
  ];
  $data['ga_pageviews_counter']['pageviews'] = [
    'title' => t('Pageview Counter'),
    'help'  => t('Pageview counter value.'),
    'field' => [
      'id' => 'numeric',
    ],
    'sort' => [
      'id' => 'standard',
    ],
    'filter' => [
      'id' => 'numeric',
    ],
    'argument' => [
      'id' => 'numeric',
    ],
  ];
  return $data;
}
